export enum ErrorCodes {
  VALIDATION_FAILURE = "VALIDATION_FAILURE",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
  REPO_ERROR = "REPO_ERROR",
  USE_CASE_ERROR = "USE_CASE_ERROR",
  API_ERROR = "API_ERROR",

  LOGIN_FAILURE = "LOGIN_FAILURE",
  MEMBER_REPO_ERROR = "MEMBER_REPO_ERROR",
  MEMBER_NOT_FOUND = "MEMBER_NOT_FOUND",

  JWT_SIGNING_ERROR = "JWT_SIGNING_ERROR",
  OTP_GENERATION_ERROR = "OTP_GENERATION_ERROR",
  OTP_VERIFICATION_ERROR = "OTP_VERIFICATION_ERROR",
  OTP_VALIDATION_FAILURE = "OTP_VALIDATION_FAILURE",
  PHONE_NOT_FOUND = "PHONE_NOT_FOUND",

  AUTH_CODE_REPO_ERROR = "AUTH_CODE_REPO_ERROR",

  SSO_CLIENT_AUTH_ERROR = "SSO_CLIENT_AUTH_ERROR",

  HTTP_CLIENT_ERROR = "HTTP_CLIENT_ERROR",

  LICENSE_REPO_ERROR = "LICENSE_REPO_ERROR",

  CRYPTO_ERROR = "CRYPTO_ERROR",
  EMAIL_DELIVERY_ERROR = "EMAIL_DELIVERY_ERROR",
  ONE_TIME_CODE_REPO_ERROR = "ONE_TIME_CODE_REPO_ERROR",
  SUBSCRIBER_REPO_ERROR = "SUBSCRIBER_REPO_ERROR",
  QUESTION_NOT_FOUND = "QUESTION_NOT_FOUND",
  QUESTION_NOT_PUBLISHED = "QUESTION_NOT_PUBLISHED",
  UNLOCKED_LEVEL_ACCESS = "UNLOCKED_LEVEL_ACCESS",
  LEVEL_ERROR = "LEVEL_ERROR",
  TAMPERED_TOKEN = "TAMPERED_TOKEN",

  FILE_STORAGE_ERROR = "FILE_STORAGE_ERROR",
  FILE_IO_ERROR = "FILE_IO_ERROR",
  JOB_NOT_FOUND = "JOB_NOT_FOUND",
  JOB_ALREADY_DISPATCHED = "JOB_ALREADY_DISPATCHED",
  QUEUE_NOT_FOUND = "QUEUE_NOT_FOUND",
  JOB_NOT_CONFIGURED = "JOB_NOT_CONFIGURED",
  AMQP_ERROR = "AMQP_ERROR",
}

export interface Error {
  code: ErrorCodes;
  status?: number;
  message?: string;
  error?: any;
}
